import type { Job } from '../../drizzle/schema/jobs'
import type { Vendor } from '../../drizzle/schema/vendors'
import type { ActivityLog } from '../../drizzle/schema/activity_log'
import type { AiRecommendation } from '../../drizzle/schema/ai_recommendations'

export const MOCK_VENDORS: Vendor[] = [
  {
    id: 1,
    name: 'Apex Repairs',
    email: 'apex@example.com',
    phone: '555-0101',
    specialty: 'HVAC',
    bio: 'Specializing in commercial HVAC systems for 12 years.',
    status: 'available',
    performanceScore: 94,
    isActive: true,
    createdAt: new Date('2023-01-10'),
    updatedAt: new Date('2024-11-01'),
  },
  {
    id: 2,
    name: 'BlueLine Services',
    email: 'blueline@example.com',
    phone: '555-0102',
    specialty: 'Plumbing',
    bio: 'Full-service plumbing for retail and commercial properties.',
    status: 'busy',
    performanceScore: 88,
    isActive: true,
    createdAt: new Date('2023-03-15'),
    updatedAt: new Date('2024-10-20'),
  },
  {
    id: 3,
    name: 'ClearVolt Electric',
    email: 'clearvolt@example.com',
    phone: '555-0103',
    specialty: 'Electrical',
    bio: 'Licensed electricians for all commercial needs.',
    status: 'available',
    performanceScore: 97,
    isActive: true,
    createdAt: new Date('2022-08-01'),
    updatedAt: new Date('2024-11-05'),
  },
  {
    id: 4,
    name: 'DuraFloor Co.',
    email: 'durafloor@example.com',
    phone: '555-0104',
    specialty: 'Flooring',
    bio: 'Commercial flooring installation and repair.',
    status: 'offline',
    performanceScore: 76,
    isActive: true,
    createdAt: new Date('2023-06-20'),
    updatedAt: new Date('2024-09-15'),
  },
  {
    id: 5,
    name: 'EverCool HVAC',
    email: 'evercool@example.com',
    phone: '555-0105',
    specialty: 'HVAC',
    bio: 'Rapid-response HVAC specialists.',
    status: 'available',
    performanceScore: 91,
    isActive: true,
    createdAt: new Date('2023-02-28'),
    updatedAt: new Date('2024-11-03'),
  },
]

export const MOCK_JOBS: Job[] = [
  {
    id: 1,
    title: 'HVAC Unit Failure – Store #42',
    description:
      'Main HVAC unit has stopped cooling. Store temperature rising. Urgent fix needed before opening.',
    customerName: 'Westfield Retail Group',
    customerEmail: 'ops@westfield.com',
    customerPhone: '555-9001',
    address: '42 Commerce Blvd, Austin TX 78701',
    status: 'pending',
    priority: 'urgent',
    assignedVendorId: null,
    createdById: 1,
    scheduledAt: null,
    completedAt: null,
    createdAt: new Date('2026-04-19T06:00:00Z'),
    updatedAt: new Date('2026-04-19T06:00:00Z'),
  },
  {
    id: 2,
    title: 'Burst Pipe – Stockroom B',
    description: 'Water pipe burst in stockroom B. Flooding risk. Immediate attention required.',
    customerName: 'Harbor Goods Inc.',
    customerEmail: 'facilities@harborgoods.com',
    customerPhone: '555-9002',
    address: '88 Industrial Way, Dallas TX 75201',
    status: 'assigned',
    priority: 'high',
    assignedVendorId: 2,
    createdById: 1,
    scheduledAt: new Date('2026-04-19T10:00:00Z'),
    completedAt: null,
    createdAt: new Date('2026-04-18T22:00:00Z'),
    updatedAt: new Date('2026-04-19T07:30:00Z'),
  },
  {
    id: 3,
    title: 'Electrical Panel Inspection',
    description: 'Annual electrical panel inspection required for insurance compliance.',
    customerName: 'Metro Superstore',
    customerEmail: 'maintenance@metrosuper.com',
    customerPhone: '555-9003',
    address: '200 Main St, Houston TX 77001',
    status: 'in_progress',
    priority: 'medium',
    assignedVendorId: 3,
    createdById: 2,
    scheduledAt: new Date('2026-04-19T09:00:00Z'),
    completedAt: null,
    createdAt: new Date('2026-04-17T14:00:00Z'),
    updatedAt: new Date('2026-04-19T09:05:00Z'),
  },
  {
    id: 4,
    title: 'Flooring Replacement – Entrance',
    description: 'Cracked tiles at main entrance. Safety hazard for customers.',
    customerName: 'Sunrise Mall',
    customerEmail: 'ops@sunrisemall.com',
    customerPhone: '555-9004',
    address: '1 Sunrise Pkwy, San Antonio TX 78201',
    status: 'completed',
    priority: 'medium',
    assignedVendorId: 4,
    createdById: 1,
    scheduledAt: new Date('2026-04-15T08:00:00Z'),
    completedAt: new Date('2026-04-16T17:00:00Z'),
    createdAt: new Date('2026-04-14T10:00:00Z'),
    updatedAt: new Date('2026-04-16T17:00:00Z'),
  },
  {
    id: 5,
    title: 'AC Maintenance – North Wing',
    description: 'Routine AC maintenance for north wing units.',
    customerName: 'Parkview Shopping Center',
    customerEmail: 'facilities@parkview.com',
    customerPhone: '555-9005',
    address: '500 Park Ave, Fort Worth TX 76101',
    status: 'pending',
    priority: 'low',
    assignedVendorId: null,
    createdById: 2,
    scheduledAt: new Date('2026-04-22T10:00:00Z'),
    completedAt: null,
    createdAt: new Date('2026-04-18T16:00:00Z'),
    updatedAt: new Date('2026-04-18T16:00:00Z'),
  },
  {
    id: 6,
    title: 'Emergency Generator Test',
    description: 'Monthly emergency generator test and maintenance check.',
    customerName: 'Westfield Retail Group',
    customerEmail: 'ops@westfield.com',
    customerPhone: '555-9001',
    address: '42 Commerce Blvd, Austin TX 78701',
    status: 'cancelled',
    priority: 'low',
    assignedVendorId: null,
    createdById: 1,
    scheduledAt: null,
    completedAt: null,
    createdAt: new Date('2026-04-10T09:00:00Z'),
    updatedAt: new Date('2026-04-11T11:00:00Z'),
  },
]

export const MOCK_ACTIVITY_LOGS: Record<number, ActivityLog[]> = {
  1: [
    {
      id: 1,
      jobId: 1,
      actorId: null,
      eventType: 'job.created',
      summary: 'Job created by system intake.',
      metadata: null,
      createdAt: new Date('2026-04-19T06:00:00Z'),
    },
  ],
  2: [
    {
      id: 2,
      jobId: 2,
      actorId: null,
      eventType: 'job.created',
      summary: 'Job created by system intake.',
      metadata: null,
      createdAt: new Date('2026-04-18T22:00:00Z'),
    },
    {
      id: 3,
      jobId: 2,
      actorId: 1,
      eventType: 'job.assigned',
      summary: 'Assigned to BlueLine Services by Dispatcher Alex.',
      metadata: { vendorId: 2, vendorName: 'BlueLine Services' },
      createdAt: new Date('2026-04-19T07:30:00Z'),
    },
  ],
  3: [
    {
      id: 4,
      jobId: 3,
      actorId: 2,
      eventType: 'job.created',
      summary: 'Job created by Vendor Manager Sam.',
      metadata: null,
      createdAt: new Date('2026-04-17T14:00:00Z'),
    },
    {
      id: 5,
      jobId: 3,
      actorId: 1,
      eventType: 'job.assigned',
      summary: 'Assigned to ClearVolt Electric by Dispatcher Alex.',
      metadata: { vendorId: 3, vendorName: 'ClearVolt Electric' },
      createdAt: new Date('2026-04-18T09:00:00Z'),
    },
    {
      id: 6,
      jobId: 3,
      actorId: null,
      eventType: 'status.changed',
      summary: 'Status changed to In Progress.',
      metadata: { from: 'assigned', to: 'in_progress' },
      createdAt: new Date('2026-04-19T09:05:00Z'),
    },
  ],
  4: [
    {
      id: 7,
      jobId: 4,
      actorId: null,
      eventType: 'job.created',
      summary: 'Job created by system intake.',
      metadata: null,
      createdAt: new Date('2026-04-14T10:00:00Z'),
    },
    {
      id: 8,
      jobId: 4,
      actorId: 1,
      eventType: 'vendor.overridden',
      summary: 'Dispatcher overrode AI recommendation. Chose DuraFloor Co. instead of Apex Repairs.',
      metadata: {
        aiSuggestedVendorId: 1,
        aiSuggestedVendorName: 'Apex Repairs',
        chosenVendorId: 4,
        chosenVendorName: 'DuraFloor Co.',
        reason: 'DuraFloor has specific flooring expertise for this job type.',
      },
      createdAt: new Date('2026-04-14T11:00:00Z'),
    },
    {
      id: 9,
      jobId: 4,
      actorId: null,
      eventType: 'status.changed',
      summary: 'Status changed to Completed.',
      metadata: { from: 'in_progress', to: 'completed' },
      createdAt: new Date('2026-04-16T17:00:00Z'),
    },
  ],
  5: [
    {
      id: 10,
      jobId: 5,
      actorId: 2,
      eventType: 'job.created',
      summary: 'Job created by Vendor Manager Sam.',
      metadata: null,
      createdAt: new Date('2026-04-18T16:00:00Z'),
    },
  ],
  6: [
    {
      id: 11,
      jobId: 6,
      actorId: null,
      eventType: 'job.created',
      summary: 'Job created by system intake.',
      metadata: null,
      createdAt: new Date('2026-04-10T09:00:00Z'),
    },
    {
      id: 12,
      jobId: 6,
      actorId: 1,
      eventType: 'status.changed',
      summary: 'Job cancelled — vendor unavailable.',
      metadata: { from: 'pending', to: 'cancelled' },
      createdAt: new Date('2026-04-11T11:00:00Z'),
    },
  ],
}

export const MOCK_AI_RECOMMENDATIONS: Record<number, AiRecommendation> = {
  1: {
    id: 1,
    jobId: 1,
    vendorId: 1,
    confidenceScore: 0.91,
    reasoning:
      'Apex Repairs has completed 14 HVAC jobs in the Austin area with a 94% satisfaction rate. They are currently available and have responded within 2 hours on average for urgent jobs.',
    rank: 1,
    wasAccepted: null,
    overriddenById: null,
    overrideReason: null,
    createdAt: new Date('2026-04-19T06:01:00Z'),
  },
  2: {
    id: 2,
    jobId: 2,
    vendorId: 2,
    confidenceScore: 0.87,
    reasoning:
      'BlueLine Services specializes in emergency plumbing and has handled 8 similar burst-pipe incidents. Closest available vendor to the Dallas location.',
    rank: 1,
    wasAccepted: true,
    overriddenById: null,
    overrideReason: null,
    createdAt: new Date('2026-04-18T22:01:00Z'),
  },
  5: {
    id: 3,
    jobId: 5,
    vendorId: 5,
    confidenceScore: 0.78,
    reasoning:
      'EverCool HVAC is available and has performed routine maintenance for similar retail properties. Moderate confidence due to scheduling constraints.',
    rank: 1,
    wasAccepted: null,
    overriddenById: null,
    overrideReason: null,
    createdAt: new Date('2026-04-18T16:01:00Z'),
  },
}
